### PR TITLE
fix compilation with GCC 15

### PR DESCRIPTION
**Pull request by envolution**
These changes allow for compilation on 3.4.0, though I don't see any tests to run so I can't validate them

### CODE REVIEW

**Comment by danc86** [comment]
The ncursesw gem already compiles and works fine on Ruby 3.4. I am using it that way right now.

What exact error is this fixing?

**Comment by danc86** [comment]
Hmm I see. Yeah this would be unrelated to Ruby 3.4, it must be coming from GCC 15. (NixOS stable is still on GCC14.)

In C23, unprototyped functions are assumed to take `void` args, rather than the traditional C meaning of "any args ignored". That would explain the errors, which are really saying that these functions now have `void` args instead of `VALUE`.

```
ncurses_wrap.h:101:30: error: passing argument 3 of ‘rb_define_singleton_method_00’ from incompatible pointer type [-Wincompatible-pointer-types]
  101 |                              &rbncurs_ ## name,   \
/usr/include/ruby-3.4.0/ruby/internal/anyargs.h:308:144: note: in definition of macro ‘rb_define_singleton_method’
  308 | #define rb_define_singleton_method(obj, mid, func, arity)   RBIMPL_ANYARGS_DISPATCH_rb_define_singleton_method((arity), (func))((obj), (mid), (func), (arity))
      |                                                                                                                                                ^~~~
ncurses_wrap.c:159:5: note: in expansion of macro ‘NCFUNC’
  159 |     NCFUNC(COLORS, 0);
      |     ^~~~~~
/usr/include/ruby-3.4.0/ruby/internal/anyargs.h:271:21: note: expected ‘VALUE (*)(VALUE)’ {aka ‘long unsigned int (*)(long unsigned int)’} but argument is of type ‘VALUE (*)(void)’ {aka ‘long unsigned int (*)(void)’}
```

Thanks for the PR. The changes look good to me at a quick glance, but I will give this a more thorough test before merging.

You are right that `-std=c17` (or anything else like `-std=c99`) should work around this.

**Comment by danc86** [comment]
Nixpkgs still doesn't have GCC 15 yet, but I was able to reproduce these errors (and a few others :thinking:) on GCC 14 by using `-std=c23`.

**Comment by danc86** [comment]
`-std=gnu23` is a better reproducer. I forgot that `-std=c23` hides a bunch of libc functions from POSIX and stuff, like `clock_gettime()` which this gem uses.

**Comment by danc86** [comment]
Thanks for the PR. I merged this to master, with some modifications to use `VALUE dummy` as the ignored argument, since that's what is used on all the other existing functions.

**Comment by envolution** [comment]
For what it's worth, the supplied pull request has been live on AUR for a couple of weeks with no reports of problems in either the ncursesw or sup packages

I have also done some limited testing on sup without problems

https://aur.archlinux.org/cgit/aur.git/log/?h=ruby-ncursesw
